### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by gmoogSPR** [seeq12/seeq-clustering#4]
Could you have more details for the installation instructions?

It says "git clone https://github.com/seeq12/seeq-clustering.git"
but when I run this in my SEEQ DataLAb project, I get:
_bash: git: command not found__

so I don't know how to add git to SDL and I am afraid to break it anyway. when I am inside a SDL project, and I run a command in the terminal, am i modifying my SEEQ server's entire configuration or is each SDL project sort of it's own environment?

Please advise on the installation steps.

**Comment by eparsonnet93** [comment]
@gmoogSPR, seeq-clustering is not yet compatible with R54. A new version, which does not require Git is in the works, but not yet available. I will update and close this issue once a version compatible with R54 is complete.

**Comment by gmoogSPR** [comment]
ok, because I am on 53.4 and indeed it doesn't have git.

**Comment by sethgilchrist** [comment]
@gmoogSPR, the git command is a short-hand for downloading the code files.  The installation instructions include it since it is a one-line, copy and paste command that replaces a few other commands, but only works if git is installed.  Lacking git, you have to do a few extra steps:

1. Go to the tool's github web page, https://github.com/seeq12/seeq-clustering
2. Click the green button labelled "Code" and select the last option "Download ZIP"
3. Go to your SDL project and upload the zip file you just downloaded. For me it was called `seeq-clustering-main.zip`
4. In your project, select New > Terminal from the page shows all the files (this is the same menu you use to create a new notebook)
5. In that terminal run the command: `python -m zipfile -e "seeq-clustering-main.zip" .`

This will create a new folder called "seeq-clustering-main" with the files you need contained within.  You can then continue following the installation instructions.

**Comment by ai-quantitative** [comment]
I tried something similar but I was running another unzipping function that wasn't installed. That worked. Thanks for the help

**Comment by gmoogSPR** [comment]
I tried something similar but I was running another unzipping function that wasn't installed either. That worked. 
Thanks for the help
